name: ci-sonarqube-docker
on: 
  pull_request:
    branches:
      - develop
jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.21.1
      - run: go test -coverprofile=coverage.out
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
    # Setup sonar-scanner
        name: Setup SonarQube
      - uses: warchant/setup-sonar-scanner@v7
    # Run sonar-scanner
        name: SonarQube Scan
      - run: sonar-scanner
      
        name: Set up QEMU
      - uses: docker/setup-qemu-action@v3
        name: Set up Docker Buildx
      - uses: docker/setup-buildx-action@v3
        name: Build and push
      - uses: docker/build-push-action@v5
        with:
          push: false
          tags: drw741/ci-sonar:latest
          
